In [1]:
try:
  %tensorflow_version 2.x
except Exception:
  pass

In [2]:
import tensorflow as tf
import numpy as np

In [9]:
def tf_constant(array):
  return tf.constant(array)

tmp_array = np.arange(1,10)
x = tf_constant(tmp_array)
x

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [11]:
def tf_square(array):
  arr=tf.constant(array)
  return tf.square(array)
tmp_array=np.arange(1, 10)
x = tf_square(tmp_array)
x

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [12]:
def tf_reshape(array,shape):
  arr=tf.constant(array)
  return tf.reshape(arr,shape=shape)
tmp_array = np.array([1,2,3,4,5,6,7,8,9])
x = tf_reshape(tmp_array, (3, 3))
x

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [13]:
def tf_cast(array,dtype):
  arr=tf.constant(array)
  return tf.cast(arr,dtype=dtype)
tmp_array = [1,2,3,4]
x = tf_cast(tmp_array, tf.float32)
x

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [14]:
def tf_multiply(t1,t2):
  return tf.multiply(t1,t2)
tmp_1 = tf.constant(np.array([[1,2],[3,4]]))
tmp_2 = tf.constant(np.array(2))
result = tf_multiply(tmp_1, tmp_2)
result

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[2, 4],
       [6, 8]])>

In [26]:
def tf_add(t1,t2):
  return tf.add(t1,t2)
tmp_1 = tf.constant(np.array([1, 2, 3]))
tmp_2 = tf.constant(np.array([4, 5, 6]))
tf_add(tmp_1, tmp_2).numpy()


array([5, 7, 9])

In [27]:
def tf_gradient_tape(x):
  with tf.GradientTape() as t:
    t.watch(x)
    y=3*x**3-2*x**2+x
    z=tf.reduce_sum(y)
  dz_dx=t.gradient(z,x)
  return dz_dx

In [28]:
tmp_x = tf.constant(2.0)
dz_dx = tf_gradient_tape(tmp_x)
result = dz_dx.numpy()
result

29.0